// <auto-generated />
using System;
using DunorGames.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DunorGames.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DunorGamesDbContext))]
    [Migration("20260823055031_InitialStatblocks")]
    partial class InitialStatblocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DunorGames.Infrastructure.Persistence.Entities.GameSystemEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("GameSystems", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "dungeonsAndDragons",
                            DisplayName = "Dungeons & Dragons",
                            SortOrder = 1
                        },
                        new
                        {
                            Code = "talesOfTheValiant",
                            DisplayName = "Tales of the Valiant",
                            SortOrder = 2
                        },
                        new
                        {
                            Code = "daggerheart",
                            DisplayName = "Daggerheart",
                            SortOrder = 3
                        },
                        new
                        {
                            Code = "drawSteel",
                            DisplayName = "Draw Steel",
                            SortOrder = 4
                        },
                        new
                        {
                            Code = "dc20",
                            DisplayName = "DC20",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("DunorGames.Infrastructure.Persistence.Entities.StatblockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("CONVERT(datetimeoffset, SYSUTCDATETIME())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("SourceReference");

                    b.Property<Guid?>("SourceStatblockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceSystemCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("SourceSystem");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("draft");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("System");

                    b.Property<string>("SystemDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("CONVERT(datetimeoffset, SYSUTCDATETIME())");

                    b.HasKey("Id");

                    b.HasIndex("SourceStatblockId");

                    b.HasIndex("SourceSystemCode");

                    b.HasIndex("SystemCode");

                    b.HasIndex("OwnerId", "UpdatedAt");

                    b.HasIndex("OwnerId", "SystemCode", "Status");

                    b.ToTable("Statblocks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Statblocks_Origin", "[Origin] IN ('manual', 'imported', 'converted')");

                            t.HasCheckConstraint("CK_Statblocks_SchemaVersion", "LEN([SchemaVersion]) > 0");

                            t.HasCheckConstraint("CK_Statblocks_Status", "[Status] IN ('draft', 'published', 'archived')");

                            t.HasCheckConstraint("CK_Statblocks_SystemDataJson", "ISJSON([SystemDataJson]) = 1");
                        });
                });

            modelBuilder.Entity("DunorGames.Infrastructure.Persistence.Entities.StatblockTagEntity", b =>
                {
                    b.Property<Guid>("StatblockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tag")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("StatblockId", "Tag");

                    b.ToTable("StatblockTags", (string)null);
                });

            modelBuilder.Entity("DunorGames.Infrastructure.Persistence.Entities.StatblockEntity", b =>
                {
                    b.HasOne("DunorGames.Infrastructure.Persistence.Entities.StatblockEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceStatblockId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DunorGames.Infrastructure.Persistence.Entities.GameSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceSystemCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DunorGames.Infrastructure.Persistence.Entities.GameSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("SystemCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DunorGames.Infrastructure.Persistence.Entities.StatblockTagEntity", b =>
                {
                    b.HasOne("DunorGames.Infrastructure.Persistence.Entities.StatblockEntity", "Statblock")
                        .WithMany("Tags")
                        .HasForeignKey("StatblockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Statblock");
                });

            modelBuilder.Entity("DunorGames.Infrastructure.Persistence.Entities.StatblockEntity", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
