// <auto-generated />
using System;
using DunorGames.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DunorGames.Data.Persistence.Migrations
{
    [DbContext(typeof(DunorGamesDbContext))]
    [Migration("20261005012140_AddDaggerheartReferenceValues")]
    partial class AddDaggerheartReferenceValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DunorGames.Data.Persistence.Entities.GameSystemEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("GameSystems", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "dungeonsAndDragons",
                            DisplayName = "Dungeons & Dragons",
                            SortOrder = 1
                        },
                        new
                        {
                            Code = "talesOfTheValiant",
                            DisplayName = "Tales of the Valiant",
                            SortOrder = 2
                        },
                        new
                        {
                            Code = "daggerheart",
                            DisplayName = "Daggerheart",
                            SortOrder = 3
                        },
                        new
                        {
                            Code = "drawSteel",
                            DisplayName = "Draw Steel",
                            SortOrder = 4
                        },
                        new
                        {
                            Code = "dc20",
                            DisplayName = "DC20",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("DunorGames.Data.Persistence.Entities.ReferenceValueEntity", b =>
                {
                    b.Property<string>("SystemCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Category")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("SystemCode", "Category", "Code");

                    b.HasIndex("SystemCode", "Category", "SortOrder");

                    b.ToTable("ReferenceValues", (string)null);

                    b.HasData(
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "tier",
                            Code = "1",
                            DisplayName = "Tier 1",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "tier",
                            Code = "2",
                            DisplayName = "Tier 2",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "tier",
                            Code = "3",
                            DisplayName = "Tier 3",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "tier",
                            Code = "4",
                            DisplayName = "Tier 4",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "adversaryType",
                            Code = "bruiser",
                            DisplayName = "Bruiser",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "adversaryType",
                            Code = "horde",
                            DisplayName = "Horde",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "adversaryType",
                            Code = "leader",
                            DisplayName = "Leader",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "adversaryType",
                            Code = "minion",
                            DisplayName = "Minion",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "adversaryType",
                            Code = "ranged",
                            DisplayName = "Ranged",
                            IsActive = true,
                            SortOrder = 5
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "adversaryType",
                            Code = "skulk",
                            DisplayName = "Skulk",
                            IsActive = true,
                            SortOrder = 6
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "adversaryType",
                            Code = "social",
                            DisplayName = "Social",
                            IsActive = true,
                            SortOrder = 7
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "adversaryType",
                            Code = "solo",
                            DisplayName = "Solo",
                            IsActive = true,
                            SortOrder = 8
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "adversaryType",
                            Code = "standard",
                            DisplayName = "Standard",
                            IsActive = true,
                            SortOrder = 9
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "adversaryType",
                            Code = "support",
                            DisplayName = "Support",
                            IsActive = true,
                            SortOrder = 10
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "attackRange",
                            Code = "melee",
                            DisplayName = "Melee",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "attackRange",
                            Code = "very close",
                            DisplayName = "Very Close",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "attackRange",
                            Code = "close",
                            DisplayName = "Close",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "attackRange",
                            Code = "far",
                            DisplayName = "Far",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "attackRange",
                            Code = "very far",
                            DisplayName = "Very Far",
                            IsActive = true,
                            SortOrder = 5
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "damageType",
                            Code = "physical",
                            DisplayName = "Physical",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "damageType",
                            Code = "magical",
                            DisplayName = "Magical",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "damageDie",
                            Code = "4",
                            DisplayName = "d4",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "damageDie",
                            Code = "6",
                            DisplayName = "d6",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "damageDie",
                            Code = "8",
                            DisplayName = "d8",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "damageDie",
                            Code = "10",
                            DisplayName = "d10",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "damageDie",
                            Code = "12",
                            DisplayName = "d12",
                            IsActive = true,
                            SortOrder = 5
                        },
                        new
                        {
                            SystemCode = "daggerheart",
                            Category = "damageDie",
                            Code = "20",
                            DisplayName = "d20",
                            IsActive = true,
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("DunorGames.Data.Persistence.Entities.StatblockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AliasesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("CONVERT(datetimeoffset, SYSUTCDATETIME())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("SourceReference");

                    b.Property<Guid?>("SourceStatblockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceSystemCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("SourceSystem");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("draft");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("System");

                    b.Property<string>("SystemDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("CONVERT(datetimeoffset, SYSUTCDATETIME())");

                    b.HasKey("Id");

                    b.HasIndex("SourceStatblockId");

                    b.HasIndex("SourceSystemCode");

                    b.HasIndex("SystemCode");

                    b.HasIndex("OwnerId", "UpdatedAt");

                    b.HasIndex("OwnerId", "SystemCode", "Status");

                    b.ToTable("Statblocks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Statblocks_Origin", "[Origin] IN ('manual', 'imported', 'converted')");

                            t.HasCheckConstraint("CK_Statblocks_SchemaVersion", "LEN([SchemaVersion]) > 0");

                            t.HasCheckConstraint("CK_Statblocks_Status", "[Status] IN ('draft', 'published', 'archived')");

                            t.HasCheckConstraint("CK_Statblocks_SystemDataJson", "ISJSON([SystemDataJson]) = 1");
                        });
                });

            modelBuilder.Entity("DunorGames.Data.Persistence.Entities.StatblockTagEntity", b =>
                {
                    b.Property<Guid>("StatblockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tag")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("StatblockId", "Tag");

                    b.ToTable("StatblockTags", (string)null);
                });

            modelBuilder.Entity("DunorGames.Data.Persistence.Entities.ReferenceValueEntity", b =>
                {
                    b.HasOne("DunorGames.Data.Persistence.Entities.GameSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("SystemCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DunorGames.Data.Persistence.Entities.StatblockEntity", b =>
                {
                    b.HasOne("DunorGames.Data.Persistence.Entities.StatblockEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceStatblockId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DunorGames.Data.Persistence.Entities.GameSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceSystemCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DunorGames.Data.Persistence.Entities.GameSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("SystemCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DunorGames.Data.Persistence.Entities.StatblockTagEntity", b =>
                {
                    b.HasOne("DunorGames.Data.Persistence.Entities.StatblockEntity", "Statblock")
                        .WithMany("Tags")
                        .HasForeignKey("StatblockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Statblock");
                });

            modelBuilder.Entity("DunorGames.Data.Persistence.Entities.StatblockEntity", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
